<?php

use App\Http\Controllers\Api\V1\AdvancedController;
use App\Http\Controllers\Api\V1\AppealController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\BrowseController;
use App\Http\Controllers\Api\V1\CatalogController;
use App\Http\Controllers\Api\V1\CommentController;
use App\Http\Controllers\Api\V1\ConnectedAccountController;
use App\Http\Controllers\Api\V1\ContentReportController;
use App\Http\Controllers\Api\V1\CreatorController;
use App\Http\Controllers\Api\V1\CreatorFollowController;
use App\Http\Controllers\Api\V1\CreatorPayoutSettingsController;
use App\Http\Controllers\Api\V1\DownloadController;
use App\Http\Controllers\Api\V1\EarnController;
use App\Http\Controllers\Api\V1\EpisodeContentController;
use App\Http\Controllers\Api\V1\EpisodeNoteController;
use App\Http\Controllers\Api\V1\EpisodeReactionController;
use App\Http\Controllers\Api\V1\GiftController;
use App\Http\Controllers\Api\V1\HomeController;
use App\Http\Controllers\Api\V1\IapController;
use App\Http\Controllers\Api\V1\InvitationController;
use App\Http\Controllers\Api\V1\LibraryController;
use App\Http\Controllers\Api\V1\ListenerStatsController;
use App\Http\Controllers\Api\V1\LiveSessionController;
use App\Http\Controllers\Api\V1\MeController;
use App\Http\Controllers\Api\V1\MediaUploadController;
use App\Http\Controllers\Api\V1\NotificationController;
use App\Http\Controllers\Api\V1\OtpController;
use App\Http\Controllers\Api\V1\PasswordController;
use App\Http\Controllers\Api\V1\PayoutMethodController;
use App\Http\Controllers\Api\V1\PlatformController;
use App\Http\Controllers\Api\V1\PlaybackController;
use App\Http\Controllers\Api\V1\PlayerSessionController;
use App\Http\Controllers\Api\V1\PremiumController;
use App\Http\Controllers\Api\V1\PushTokenController;
use App\Http\Controllers\Api\V1\PrivacyRequestController;
use App\Http\Controllers\Api\V1\ProfileController;
use App\Http\Controllers\Api\V1\PublicLiveController;
use App\Http\Controllers\Api\V1\QueueController;
use App\Http\Controllers\Api\V1\ReelController;
use App\Http\Controllers\Api\V1\ReelDraftController;
use App\Http\Controllers\Api\V1\ReelEngagementController;
use App\Http\Controllers\Api\V1\ReelMonetizationController;
use App\Http\Controllers\Api\V1\SearchHistoryController;
use App\Http\Controllers\Api\V1\ShowReviewController;
use App\Http\Controllers\Api\V1\SocialAuthController;
use App\Http\Controllers\Api\V1\StudioController;
use App\Http\Controllers\Api\V1\StudioWorkspaceController;
use App\Http\Controllers\Api\V1\SupportController;
use App\Http\Controllers\Api\V1\WithdrawalController;
use App\Support\ApiResponse;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::get('cms/help', [SupportController::class, 'help']);
    Route::get('cms/about', [SupportController::class, 'about']);
    Route::get('cms/guidelines', [SupportController::class, 'guidelines']);
    Route::get('cms/{slug}', [SupportController::class, 'cms'])->whereIn('slug', ['terms', 'privacy']);
    Route::middleware('throttle:auth')->group(function (): void {
        Route::post('auth/register', [AuthController::class, 'register']);
        Route::post('auth/login', [AuthController::class, 'login']);
        Route::post('auth/social', SocialAuthController::class);
        Route::post('auth/refresh', [AuthController::class, 'refresh']);
        Route::post('auth/otp/send', [OtpController::class, 'send'])->middleware('throttle:5,1');
        Route::post('auth/otp/verify', [OtpController::class, 'verify'])->middleware('throttle:10,1');
        Route::post('auth/password/forgot', [PasswordController::class, 'forgot'])->middleware('throttle:5,1');
        Route::post('auth/password/reset', [PasswordController::class, 'reset'])->middleware('throttle:10,1');
    });
    Route::middleware('auth:sanctum')->group(function (): void {
        Route::get('me', [MeController::class, 'show']);
        Route::patch('me', [ProfileController::class, 'update']);
        Route::post('me/avatar', [ProfileController::class, 'avatar'])->middleware('throttle:10,1');
        Route::patch('me/password', [PasswordController::class, 'update']);
        Route::put('me/onboarding', [ProfileController::class, 'onboarding']);
        Route::get('me/preferences', [ProfileController::class, 'preferences']);
        Route::patch('me/preferences', [ProfileController::class, 'updatePreferences']);
        Route::get('me/connected-accounts', [ConnectedAccountController::class, 'index']);
        Route::post('me/connected-accounts', [ConnectedAccountController::class, 'store']);
        Route::delete('me/connected-accounts/{account}', [ConnectedAccountController::class, 'destroy']);
        Route::get('me/invite', [InvitationController::class, 'show']);
        Route::post('me/invite', [InvitationController::class, 'store']);
        Route::post('referrals/redeem', [InvitationController::class, 'redeem']);
        Route::post('me/data-export', [PrivacyRequestController::class, 'export'])->middleware('throttle:2,60');
        Route::get('me/data-export/{export}', [PrivacyRequestController::class, 'exportStatus']);
        Route::get('me/data-export/{export}/download', [PrivacyRequestController::class, 'download'])->middleware('signed')->name('api.me.data-export.download');
        Route::post('me/delete', [PrivacyRequestController::class, 'delete'])->middleware('throttle:2,60');
        Route::get('me/config', [MeController::class, 'config']);
        Route::get('me/following', [CatalogController::class, 'following']);
        Route::post('auth/logout', [AuthController::class, 'logout']);
        Route::get('home/feed', [HomeController::class, 'feed']);
        Route::get('home/rails/{rail}', [HomeController::class, 'rail']);
        Route::get('home/discover', [HomeController::class, 'discover']);
        Route::get('home/charts', [HomeController::class, 'charts']);
        Route::get('home/playlists', [HomeController::class, 'playlists']);
        Route::get('home/recommendations', [HomeController::class, 'recommendations']);
        Route::get('search', [CatalogController::class, 'search']);
        Route::get('search/recent', [SearchHistoryController::class, 'index']);
        Route::post('search/recent', [SearchHistoryController::class, 'store']);
        Route::delete('search/recent/{id}', [SearchHistoryController::class, 'destroyOne']);
        Route::delete('search/recent', [SearchHistoryController::class, 'destroy']);
        Route::post('search/voice', [CatalogController::class, 'voiceSearch']);
        Route::get('browse', [BrowseController::class, 'index']);
        Route::get('browse/categories', [BrowseController::class, 'categories']);
        Route::get('browse/{slug}', [BrowseController::class, 'show']);
        Route::get('shows/{show}', [CatalogController::class, 'show'])->name('api.show');
        Route::get('shows/{show}/episodes', [CatalogController::class, 'episodes']);
        Route::get('shows/{show}/related', [CatalogController::class, 'related']);
        Route::get('shows/{show}/reviews', [ShowReviewController::class, 'index']);
        Route::post('shows/{show}/reviews', [ShowReviewController::class, 'store']);
        Route::patch('reviews/{review}', [ShowReviewController::class, 'update']);
        Route::delete('reviews/{review}', [ShowReviewController::class, 'destroy']);
        Route::post('shows/{show}/follow', [CatalogController::class, 'follow']);
        Route::delete('shows/{show}/follow', [CatalogController::class, 'unfollow']);
        Route::put('shows/{show}/notifications', [CatalogController::class, 'notifications']);
        Route::put('shows/{show}/rating', [CatalogController::class, 'rate']);
        Route::post('shows/{show}/refresh', [CatalogController::class, 'refresh']);
        Route::get('episodes/{episode}', [CatalogController::class, 'episode']);
        Route::get('episodes/{episode}/chapters', [EpisodeContentController::class, 'chapters']);
        Route::get('episodes/{episode}/transcript', [EpisodeContentController::class, 'transcript']);
        Route::get('episodes/{episode}/stream', [EpisodeContentController::class, 'stream']);
        Route::get('episodes/{episode}/notes', [EpisodeNoteController::class, 'show']);
        Route::put('episodes/{episode}/notes', [EpisodeNoteController::class, 'update']);
        Route::delete('episodes/{episode}/notes', [EpisodeNoteController::class, 'destroy']);
        Route::put('episodes/{episode}/reaction', [EpisodeReactionController::class, 'store']);
        Route::delete('episodes/{episode}/reaction', [EpisodeReactionController::class, 'destroy']);
        Route::post('episodes/{episode}/like', [EpisodeReactionController::class, 'like']);
        Route::delete('episodes/{episode}/like', [EpisodeReactionController::class, 'destroy']);
        Route::post('downloads/authorize/{episode}', [EpisodeContentController::class, 'authorizeDownload']);
        Route::post('episodes/{episode}/downloads', [EpisodeContentController::class, 'authorizeDownload']);
        Route::get('playback/{episode}', [PlaybackController::class, 'show']);
        Route::put('playback/{episode}', [PlaybackController::class, 'update']);
        Route::get('player/session', [PlayerSessionController::class, 'show']);
        Route::patch('player/session', [PlayerSessionController::class, 'update']);
        Route::get('gifts/catalog', [GiftController::class, 'catalog']);
        Route::get('gifts/wallet', [GiftController::class, 'wallet']);
        Route::get('gifts/wallet/activity', [GiftController::class, 'activity']);
        Route::get('gifts/packs', [GiftController::class, 'packs']);
        Route::get('gifts/{gift}', [GiftController::class, 'show']);
        Route::post('iap/verify', [IapController::class, 'store'])->middleware('throttle:10,1');
        Route::post('gifts/send', [GiftController::class, 'send']);
        Route::post('earn/episodes/{episode}/sessions', [EarnController::class, 'start']);
        Route::post('earn/sessions/{session}/heartbeat', [EarnController::class, 'heartbeat']);
        Route::post('earn/sessions/{session}/complete', [EarnController::class, 'complete']);
        Route::get('earn/wallet', [EarnController::class, 'wallet']);
        Route::get('earn/shows', [EarnController::class, 'shows']);
        Route::get('earn/episodes', [EarnController::class, 'episodes']);
        Route::post('comments', [CommentController::class, 'store'])->middleware(['throttle:30,1', 'not.sanctioned']);
        Route::get('comments', [CommentController::class, 'index']);
        Route::patch('comments/{comment}', [CommentController::class, 'update']);
        Route::delete('comments/{comment}', [CommentController::class, 'destroy']);
        Route::post('comments/{comment}/like', [CommentController::class, 'like']);
        Route::delete('comments/{comment}/like', [CommentController::class, 'unlike']);
        Route::put('comments/{comment}/pin', [CommentController::class, 'pin']);
        Route::delete('comments/{comment}/pin', [CommentController::class, 'unpin']);
        Route::put('comments/{comment}/hide', [CommentController::class, 'hide']);
        Route::post('reports', [ContentReportController::class, 'store'])->middleware('not.sanctioned');
        Route::get('appeals', [AppealController::class, 'index']);
        Route::post('appeals', [AppealController::class, 'store'])->middleware('throttle:5,60');
        Route::post('creators/{creator}/follow', [CreatorFollowController::class, 'store']);
        Route::delete('creators/{creator}/follow', [CreatorFollowController::class, 'destroy']);
        Route::post('shows/{show}/claims', [CreatorController::class, 'claim']);
        Route::post('claims/{claim}/verify', [CreatorController::class, 'verify']);
        Route::get('claims/{claim}', [CreatorController::class, 'showClaim']);
        Route::post('claims/{claim}/challenge', [CreatorController::class, 'resend'])->middleware('throttle:5,60');
        Route::post('claims/{claim}/description/confirm', [CreatorController::class, 'confirmDescription']);
        Route::get('studio', [CreatorController::class, 'studio']);
        Route::get('studio/shows', [StudioWorkspaceController::class, 'shows']);
        Route::get('studio/episodes', [StudioWorkspaceController::class, 'episodes']);
        Route::post('studio/episodes', [StudioWorkspaceController::class, 'storeEpisode']);
        Route::get('studio/episodes/{episode}', [StudioWorkspaceController::class, 'episode']);
        Route::post('studio/episodes/{episode}/audio', [StudioWorkspaceController::class, 'uploadEpisodeAudio'])->middleware('not.sanctioned');
        Route::post('studio/episodes/{episode}/publish', [StudioWorkspaceController::class, 'publishEpisode'])->middleware('not.sanctioned');
        Route::get('studio/reels', [StudioWorkspaceController::class, 'reels']);
        Route::get('studio/reels/{reel}', [StudioWorkspaceController::class, 'reel']);
        Route::get('studio/audience', [StudioWorkspaceController::class, 'audience']);
        Route::get('studio/audience/followers', [StudioWorkspaceController::class, 'followers']);
        Route::get('studio/audience/supporters', [StudioWorkspaceController::class, 'supporters']);
        Route::get('studio/monetization', [StudioWorkspaceController::class, 'monetization']);
        Route::get('studio/payout-settings', [CreatorPayoutSettingsController::class, 'show']);
        Route::put('studio/payout-settings', [CreatorPayoutSettingsController::class, 'update']);
        Route::get('studio/transactions', [StudioWorkspaceController::class, 'transactions']);
        Route::get('studio/transactions/{transaction}', [StudioWorkspaceController::class, 'transaction']);
        Route::post('studio/live', [LiveSessionController::class, 'store'])->middleware('not.sanctioned');
        Route::patch('studio/live/{session}', [LiveSessionController::class, 'transition']);
        Route::post('studio/live/{session}/health', [LiveSessionController::class, 'health']);
        Route::apiResource('studios', StudioController::class);
        Route::post('studios/{studio}/members', [StudioController::class, 'addMember']);
        Route::post('sync/push', [AdvancedController::class, 'syncPush']);
        Route::get('sync/pull', [AdvancedController::class, 'syncPull']);
        Route::get('sync/conflicts', [AdvancedController::class, 'conflicts']);
        Route::put('sync/conflicts/{conflict}', [AdvancedController::class, 'resolveConflict']);
        Route::post('ai/jobs', [AdvancedController::class, 'aiJob']);
        Route::get('ai/jobs/{job}', [AdvancedController::class, 'aiShow']);
        Route::get('devices', [PlatformController::class, 'devices']);
        Route::post('devices/pairing-code', [PlatformController::class, 'pairingCode'])->middleware('throttle:5,1');
        Route::post('devices/pair', [PlatformController::class, 'pair'])->middleware('throttle:10,1');
        Route::delete('devices/{device}', [PlatformController::class, 'revoke']);
        Route::post('devices/sign-out-all', [PlatformController::class, 'signOutAll']);
        Route::post('backups', [PlatformController::class, 'backup']);
        Route::post('backups/{backup}/restore', [PlatformController::class, 'restore']);
        Route::get('storage', [PlatformController::class, 'storage']);
        Route::delete('storage/cache', [PlatformController::class, 'clearCache']);
        Route::get('share-card-templates', [PlatformController::class, 'shareTemplates']);
        Route::get('share-cards', [PlatformController::class, 'shares']);
        Route::post('share-cards', [PlatformController::class, 'createShare']);
        Route::get('share-cards/{card}', [PlatformController::class, 'share']);
        Route::get('reels/for-you', [ReelController::class, 'feed']);
        Route::get('reels/following', [ReelController::class, 'following']);
        Route::get('reels/trending', [ReelController::class, 'trending']);
        Route::apiResource('reels/drafts', ReelDraftController::class)->parameters(['drafts' => 'id']);
        Route::get('reels/monetization', [ReelMonetizationController::class, 'show']);
        Route::post('reels/monetization/opt-in', [ReelMonetizationController::class, 'store']);
        Route::get('reels/{reel}', [ReelController::class, 'show']);
        Route::get('reels/{reel}/related-show', [ReelController::class, 'relatedShow']);
        Route::post('reels', [ReelController::class, 'store'])->middleware('not.sanctioned');
        Route::post('reels/{reel}/episode-links', [ReelController::class, 'linkEpisode']);
        Route::post('uploads', [MediaUploadController::class, 'store'])->middleware('not.sanctioned');
        Route::get('uploads/{upload}', [MediaUploadController::class, 'show']);
        Route::post('uploads/{upload}/complete', [MediaUploadController::class, 'complete']);
        Route::put('reels/{reel}/engagement', [ReelEngagementController::class, 'update']);
        Route::post('reels/{reel}/like', [ReelEngagementController::class, 'like']);
        Route::delete('reels/{reel}/like', [ReelEngagementController::class, 'unlike']);
        Route::post('reels/{reel}/save', [ReelEngagementController::class, 'save']);
        Route::delete('reels/{reel}/save', [ReelEngagementController::class, 'unsave']);
        Route::post('reels/{reel}/not-interested', [ReelEngagementController::class, 'notInterested']);
        Route::post('reels/{reel}/view-heartbeat', [ReelEngagementController::class, 'heartbeat']);
        Route::get('live-sessions', [LiveSessionController::class, 'index']);
        Route::post('live-sessions', [LiveSessionController::class, 'store'])->middleware('not.sanctioned');
        Route::put('live-sessions/{session}/state', [LiveSessionController::class, 'transition']);
        Route::post('live-sessions/{session}/health', [LiveSessionController::class, 'health']);
        Route::get('premium/plans', [PremiumController::class, 'plans']);
        Route::get('premium/me', [PremiumController::class, 'me']);
        Route::get('premium/invoices', [PremiumController::class, 'invoices']);
        Route::get('premium/exclusive', [PremiumController::class, 'exclusive']);
        Route::post('premium/checkout', [PremiumController::class, 'checkout']);
        Route::post('premium/change-plan', [PremiumController::class, 'changePlan']);
        Route::post('premium/restore', [PremiumController::class, 'restore']);
        Route::get('withdrawals', [WithdrawalController::class, 'index']);
        Route::post('withdrawals', [WithdrawalController::class, 'store']);
        Route::get('payout-methods', [PayoutMethodController::class, 'index']);
        Route::post('payout-methods', [PayoutMethodController::class, 'store'])->middleware('throttle:5,1');
        Route::get('library', [LibraryController::class, 'index']);
        Route::get('library/saved', [LibraryController::class, 'saved']);
        Route::get('library/liked', [LibraryController::class, 'liked']);
        Route::get('library/shows', [LibraryController::class, 'shows']);
        Route::get('library/recent', [LibraryController::class, 'recent']);
        Route::get('library/settings', [LibraryController::class, 'settings']);
        Route::patch('library/settings', [LibraryController::class, 'updateSettings']);
        Route::post('episodes/{episode}/save', [LibraryController::class, 'saveEpisode']);
        Route::delete('episodes/{episode}/save', [LibraryController::class, 'unsaveEpisode']);
        Route::get('playlists', [LibraryController::class, 'playlists']);
        Route::post('playlists', [LibraryController::class, 'storePlaylist']);
        Route::get('playlists/{playlist}', [LibraryController::class, 'showPlaylist']);
        Route::put('playlists/{playlist}', [LibraryController::class, 'updatePlaylist']);
        Route::delete('playlists/{playlist}', [LibraryController::class, 'deletePlaylist']);
        Route::post('playlists/{playlist}/items', [LibraryController::class, 'addPlaylistItem']);
        Route::get('collections', [LibraryController::class, 'collections']);
        Route::post('collections', [LibraryController::class, 'storeCollection']);
        Route::get('collections/{collection}', [LibraryController::class, 'showCollection']);
        Route::put('collections/{collection}', [LibraryController::class, 'updateCollection']);
        Route::delete('collections/{collection}', [LibraryController::class, 'deleteCollection']);
        Route::get('queue', [QueueController::class, 'show']);
        Route::put('queue', [QueueController::class, 'replace']);
        Route::post('queue/items', [QueueController::class, 'add']);
        Route::post('episodes/{episode}/queue', [QueueController::class, 'addEpisode']);
        Route::delete('episodes/{episode}/queue', [QueueController::class, 'removeEpisode']);
        Route::delete('queue/items/{item}', [QueueController::class, 'remove']);
        Route::put('queue/reorder', [QueueController::class, 'replace']);
        Route::delete('queue', [QueueController::class, 'clear']);
        Route::get('downloads', [DownloadController::class, 'index']);
        Route::get('downloads/settings', [DownloadController::class, 'settings']);
        Route::patch('downloads/settings', [DownloadController::class, 'updateSettings']);
        Route::delete('downloads/{download}', [DownloadController::class, 'destroy']);
        Route::get('stats/me', ListenerStatsController::class);
        Route::get('notifications', [NotificationController::class, 'index']);
        Route::post('notifications/bulk', [NotificationController::class, 'bulk'])->middleware('throttle:30,1');
        Route::post('notifications/clear', [NotificationController::class, 'clear'])->middleware('throttle:10,1');
        Route::put('notifications/{notification}/read', [NotificationController::class, 'read']);
        Route::get('notification-preferences', [NotificationController::class, 'preferences']);
        Route::patch('notification-preferences', [NotificationController::class, 'updatePreferences'])->middleware('throttle:30,1');
        Route::put('notification-preferences', [NotificationController::class, 'updatePreferences']);
        Route::get('notification-lock-rules', [NotificationController::class, 'lockRules']);
        Route::put('notification-lock-rules', [NotificationController::class, 'updateLockRules']);
        Route::post('me/push-tokens', [PushTokenController::class, 'store'])->middleware('throttle:20,1');
        Route::delete('me/push-tokens', [PushTokenController::class, 'destroy'])->middleware('throttle:20,1');
        Route::post('support/tickets', [SupportController::class, 'ticket'])->middleware('throttle:10,1');
        Route::post('support/feedback', [SupportController::class, 'feedback'])->middleware('throttle:10,1');
    });
});
Route::get('v1/live', [PublicLiveController::class, 'index']);
Route::get('v1/live/{session}', [PublicLiveController::class, 'show']);
Route::put('v1/uploads/{upload}/content', [MediaUploadController::class, 'put'])->middleware(['signed', 'throttle:60,1'])->name('api.uploads.put');
Route::get('readiness', fn () => ApiResponse::success(['database' => DB::select('select 1') ? 'ok' : 'failed', 'cache' => Cache::put('readiness', true, 5) ? 'ok' : 'failed']))->middleware('auth:sanctum');
