<?php

use App\Http\Controllers\Admin\AdminAccountController;
use App\Http\Controllers\Admin\AdminPasswordResetController;
use App\Http\Controllers\Admin\AdminSearchController;
use App\Http\Controllers\Admin\AdvancedOperationsController;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\CanonicalDetailController;
use App\Http\Controllers\Admin\CatalogMergeController;
use App\Http\Controllers\Admin\CatalogOperationsController;
use App\Http\Controllers\Admin\ClaimReviewController;
use App\Http\Controllers\Admin\ClaimWorkspaceController;
use App\Http\Controllers\Admin\CommunicationsWorkspaceController;
use App\Http\Controllers\Admin\ConfigurationWorkspaceController;
use App\Http\Controllers\Admin\CreatorOperationsController;
use App\Http\Controllers\Admin\CreatorPayoutController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\FinanceController;
use App\Http\Controllers\Admin\IntegrationSettingsController;
use App\Http\Controllers\Admin\ModerationController;
use App\Http\Controllers\Admin\ModerationOperationsController;
use App\Http\Controllers\Admin\ModerationQueueController;
use App\Http\Controllers\Admin\ModuleWorkspaceController;
use App\Http\Controllers\Admin\OperationsController;
use App\Http\Controllers\Admin\SupportWorkspaceController;
use App\Http\Controllers\Admin\UserOperationsController;
use App\Http\Controllers\Admin\WorkspaceToolsController;
use App\Http\Controllers\MarketingController;
use App\Http\Controllers\WebhookController;
use Illuminate\Support\Facades\Route;

Route::get('/', [MarketingController::class, 'home'])->name('home');
Route::get('/how-it-works', [MarketingController::class, 'howItWorks'])->name('how-it-works');
Route::get('/privacy', [MarketingController::class, 'privacy'])->name('privacy');
Route::get('/terms', [MarketingController::class, 'terms'])->name('terms');
Route::get('/contact', [MarketingController::class, 'contact'])->name('contact');
Route::post('/contact', [MarketingController::class, 'submitContact'])->middleware('throttle:contact')->name('contact.store');
Route::get('/operations/health', [OperationsController::class, 'readiness'])->middleware('throttle:60,1')->name('operations.health');

Route::post('/webhooks/v1/{provider}', WebhookController::class)->whereIn('provider', ['paystack', 'flutterwave', 'apple', 'google']);

Route::prefix('api/admin/v1')->middleware(['auth.admin', 'admin.mfa'])->group(function (): void {
    Route::post('configuration-versions', [ConfigurationWorkspaceController::class, 'store'])->middleware(['admin.permission:settings.write', 'admin.mfa.fresh']);
    Route::get('operations/diagnostics', [OperationsController::class, 'diagnostics'])->middleware('admin.permission:audit.view');
    Route::post('operations/tasks/{task}/run', [OperationsController::class, 'run'])->where('task', '.*')->middleware(['admin.permission:operations.manage', 'admin.mfa.fresh', 'throttle:operations']);
    Route::post('operations/failed-jobs/{job}/retry', [OperationsController::class, 'retry'])->middleware(['admin.permission:operations.manage', 'admin.mfa.fresh', 'throttle:operations']);
    Route::get('communications/audience', [CommunicationsWorkspaceController::class, 'audience'])->middleware('admin.permission:broadcast.send');
    Route::post('communications/broadcasts/{broadcast}/cancel', [CommunicationsWorkspaceController::class, 'cancel'])->middleware(['admin.permission:broadcast.send', 'admin.mfa.fresh']);
    Route::put('integrations/{provider}', [IntegrationSettingsController::class, 'update'])->middleware(['admin.permission:settings.write', 'admin.mfa.fresh']);
    Route::post('integrations/{provider}/test', [IntegrationSettingsController::class, 'test'])->middleware(['admin.permission:settings.write', 'admin.mfa.fresh']);
    Route::put('support/tickets/{ticket}', [SupportWorkspaceController::class, 'update'])->middleware('admin.permission:users.view');
    Route::post('support/tickets/{ticket}/attachments', [SupportWorkspaceController::class, 'attach'])->middleware(['admin.permission:users.view', 'throttle:10,1']);
    Route::post('support/tickets/{ticket}/links', [SupportWorkspaceController::class, 'link'])->middleware('admin.permission:users.view');
    Route::get('support/tickets/{ticket}/attachments/{attachment}', [SupportWorkspaceController::class, 'attachment'])->middleware('admin.permission:users.view');
    Route::get('workspaces/{module}/tools', [WorkspaceToolsController::class, 'index']);
    Route::post('workspaces/{module}/views', [WorkspaceToolsController::class, 'save'])->middleware('throttle:30,1');
    Route::delete('workspaces/{module}/views/{view}', [WorkspaceToolsController::class, 'destroy']);
    Route::post('workspaces/{module}/exports', [WorkspaceToolsController::class, 'export'])->middleware('throttle:5,1');
    Route::get('workspaces/{module}/exports/{export}', [WorkspaceToolsController::class, 'download'])->name('admin.exports.download');
    Route::get('search', AdminSearchController::class)->middleware('throttle:60,1');
    Route::get('claims', [ClaimReviewController::class, 'index'])->middleware('admin.permission:claims.decide');
    Route::get('claims/{claim}', [ClaimReviewController::class, 'show'])->middleware('admin.permission:claims.decide');
    Route::post('claims/{claim}/live-rss', [ClaimReviewController::class, 'live'])->middleware('admin.permission:claims.decide');
    Route::post('claims/{claim}/challenge', [ClaimReviewController::class, 'requestNewCode'])->middleware('admin.permission:claims.decide');
    Route::put('claims/{claim}', [ClaimReviewController::class, 'update'])->middleware('admin.permission:claims.decide');
    Route::get('creators', [CreatorOperationsController::class, 'index'])->middleware('admin.permission:claims.decide');
    Route::get('creators/{creator}', [CreatorOperationsController::class, 'show'])->middleware('admin.permission:claims.decide');
    Route::put('claim-disputes/{dispute}', [CreatorOperationsController::class, 'dispute'])->middleware('admin.permission:claims.decide');
    Route::put('comments/{comment}/moderation', [ModerationController::class, 'comment'])->middleware('admin.permission:moderation.act');
    Route::put('reels/{reel}/moderation', [ModerationController::class, 'reel'])->middleware('admin.permission:moderation.act');
    Route::get('moderation', [ModerationQueueController::class, 'index'])->middleware('admin.permission:moderation.act');
    Route::get('moderation/reels/{reel}', [ModerationOperationsController::class, 'reel'])->middleware('admin.permission:moderation.act');
    Route::get('moderation/comments/{comment}', [ModerationOperationsController::class, 'comment'])->middleware('admin.permission:moderation.act');
    Route::get('moderation/reports/{report}', [ModerationOperationsController::class, 'report'])->middleware('admin.permission:moderation.act');
    Route::put('moderation/reports/{report}', [ModerationOperationsController::class, 'resolveReport'])->middleware('admin.permission:moderation.act');
    Route::post('moderation/sanctions', [ModerationOperationsController::class, 'sanction'])->middleware(['admin.permission:moderation.act', 'admin.mfa.fresh']);
    Route::put('moderation/appeals/{appeal}', [ModerationOperationsController::class, 'appeal'])->middleware('admin.permission:moderation.act');
    Route::get('moderation/live/{session}', [ModerationOperationsController::class, 'live'])->middleware('admin.permission:moderation.act');
    Route::post('moderation/live/{session}/takedown', [ModerationOperationsController::class, 'takedown'])->middleware(['admin.permission:moderation.act', 'admin.mfa.fresh']);
    Route::get('finance', [FinanceController::class, 'index'])->middleware('admin.permission:finance.view');
    Route::get('catalog', [CatalogOperationsController::class, 'index'])->middleware('admin.permission:catalog.write');
    Route::get('catalog/shows/{show}', [CatalogOperationsController::class, 'show'])->middleware('admin.permission:catalog.write');
    Route::post('catalog/shows/{show}/refresh', [CatalogOperationsController::class, 'refresh'])->middleware('admin.permission:catalog.write');
    Route::put('catalog/categories', [CatalogOperationsController::class, 'category'])->middleware('admin.permission:catalog.write');
    Route::put('catalog/playlists', [CatalogOperationsController::class, 'playlist'])->middleware('admin.permission:catalog.write');
    Route::put('catalog/home-modules/{module}', [CatalogOperationsController::class, 'homeModule'])->middleware(['admin.permission:catalog.write', 'admin.mfa.fresh']);
    Route::put('catalog/search-synonyms', [CatalogOperationsController::class, 'synonym'])->middleware('admin.permission:catalog.write');
    Route::post('catalog/merges/preview', [CatalogMergeController::class, 'preview'])->middleware('admin.permission:catalog.write');
    Route::post('catalog/merges', [CatalogMergeController::class, 'store'])->middleware(['admin.permission:catalog.write', 'admin.mfa.fresh']);
    Route::get('catalog/merges/{merge}', [CatalogMergeController::class, 'show'])->middleware('admin.permission:catalog.write');
    Route::get('finance/transactions/{transaction}', [FinanceController::class, 'transaction'])->middleware('admin.permission:finance.view');
    Route::post('finance/transactions/{transaction}/reversal', [FinanceController::class, 'reverse'])->middleware(['admin.permission:finance.adjust', 'admin.mfa.fresh']);
    Route::put('finance/withdrawals/{withdrawal}', [FinanceController::class, 'withdrawal'])->middleware(['admin.permission:payouts.approve', 'admin.mfa.fresh']);
    Route::put('finance/earn/{session}', [FinanceController::class, 'earn'])->middleware(['admin.permission:finance.adjust', 'admin.mfa.fresh']);
    Route::post('finance/reconciliation', [FinanceController::class, 'reconcile'])->middleware(['admin.permission:finance.adjust', 'admin.mfa.fresh']);
    Route::post('finance/settlements', [FinanceController::class, 'importSettlement'])->middleware(['admin.permission:finance.adjust', 'admin.mfa.fresh']);
    Route::put('finance/exceptions/{exception}', [FinanceController::class, 'resolveException'])->middleware(['admin.permission:finance.adjust', 'admin.mfa.fresh']);
    Route::post('finance/creator-payout-batches', [CreatorPayoutController::class, 'store'])->middleware(['admin.permission:payouts.approve', 'admin.mfa.fresh']);
    Route::get('finance/creator-payout-batches/{batch}', [CreatorPayoutController::class, 'show'])->middleware('admin.permission:finance.view');
    Route::post('finance/creator-payout-batches/{batch}/approval', [CreatorPayoutController::class, 'approve'])->middleware(['admin.permission:payouts.approve', 'admin.mfa.fresh']);
    Route::put('finance/creator-settings/{creator}', [FinanceController::class, 'creatorCompliance'])->middleware(['admin.permission:payouts.approve', 'admin.mfa.fresh']);
    Route::put('finance/premium/plans', [FinanceController::class, 'premiumPlan'])->middleware(['admin.permission:finance.adjust', 'admin.mfa.fresh']);
    Route::post('finance/fees', [FinanceController::class, 'feeVersion'])->middleware(['admin.permission:finance.adjust', 'admin.mfa.fresh']);
    Route::post('finance/fx', [FinanceController::class, 'fxVersion'])->middleware(['admin.permission:finance.adjust', 'admin.mfa.fresh']);
    Route::put('settings/fx', [FinanceController::class, 'fxVersion'])->middleware(['admin.permission:finance.adjust', 'admin.mfa.fresh']);
    Route::post('finance/coin-products', [FinanceController::class, 'coinProduct'])->middleware(['admin.permission:finance.adjust', 'admin.mfa.fresh']);
    Route::put('finance/coin-products/{product}', [FinanceController::class, 'coinProductState'])->middleware(['admin.permission:finance.adjust', 'admin.mfa.fresh']);
    Route::post('finance/gift-types', [FinanceController::class, 'giftType'])->middleware(['admin.permission:finance.adjust', 'admin.mfa.fresh']);
    Route::put('finance/gift-types/{giftType}', [FinanceController::class, 'giftTypeUpdate'])->middleware(['admin.permission:finance.adjust', 'admin.mfa.fresh']);
    Route::get('advanced', [AdvancedOperationsController::class, 'index'])->middleware('admin.permission:audit.view');
    Route::put('advanced/cms', [AdvancedOperationsController::class, 'cms'])->middleware(['admin.permission:settings.write', 'admin.mfa.fresh']);
    Route::post('advanced/prompts', [AdvancedOperationsController::class, 'prompt'])->middleware(['admin.permission:ai.manage', 'admin.mfa.fresh']);
    Route::post('advanced/referral-programs', [AdvancedOperationsController::class, 'referralProgram'])->middleware(['admin.permission:settings.write', 'admin.mfa.fresh']);
    Route::put('advanced/support/{ticket}', [AdvancedOperationsController::class, 'support'])->middleware('admin.permission:users.view');
    Route::post('advanced/notification-templates', [AdvancedOperationsController::class, 'notificationTemplate'])->middleware(['admin.permission:broadcast.send', 'admin.mfa.fresh']);
    Route::post('advanced/broadcasts', [AdvancedOperationsController::class, 'broadcast'])->middleware(['admin.permission:broadcast.send', 'admin.mfa.fresh']);
    Route::put('users/{user}/access', [UserOperationsController::class, 'access'])->middleware(['admin.permission:users.suspend', 'admin.mfa.fresh']);
});

Route::prefix('admin')->name('admin.')->group(function (): void {
    Route::middleware('guest:admin')->group(function (): void {
        Route::get('login', [AuthController::class, 'create'])->name('login');
        Route::post('login', [AuthController::class, 'store'])->middleware('throttle:auth');
        Route::get('forgot-password', [AdminPasswordResetController::class, 'requestForm'])->name('password.request');
        Route::post('forgot-password', [AdminPasswordResetController::class, 'send'])->middleware('throttle:5,1')->name('password.email');
        Route::get('reset-password/{token}', [AdminPasswordResetController::class, 'resetForm'])->name('password.reset');
        Route::post('reset-password', [AdminPasswordResetController::class, 'reset'])->middleware('throttle:10,1')->name('password.update');
        Route::get('mfa', [AuthController::class, 'challenge'])->name('mfa.create');
        Route::post('mfa', [AuthController::class, 'verify'])->middleware('throttle:auth');
        Route::get('mfa/enrol', [AuthController::class, 'enrol'])->name('mfa.enrol');
        Route::post('mfa/enrol', [AuthController::class, 'confirmEnrolment'])->middleware('throttle:auth');
        Route::get('mfa/recovery', [AuthController::class, 'recovery'])->name('mfa.recovery');
    });
    Route::middleware('auth.admin')->group(function (): void {
        Route::get('step-up', [AuthController::class, 'stepUp'])->name('step-up');
        Route::post('step-up', [AuthController::class, 'verifyStepUp'])->middleware('throttle:auth');
    });
    Route::middleware(['auth.admin', 'admin.mfa'])->group(function (): void {
        Route::get('/', DashboardController::class)->name('dashboard');
        Route::get('operations', [OperationsController::class, 'page'])->middleware('admin.permission:audit.view')->name('operations');
        Route::get('moderation', [ModerationQueueController::class, 'page'])->middleware('admin.permission:moderation.act')->name('moderation');
        Route::get('claims', ClaimWorkspaceController::class)->middleware('admin.permission:claims.decide')->name('claims');
        Route::get('creators', [CreatorOperationsController::class, 'page'])->middleware('admin.permission:claims.decide')->name('creators');
        Route::get('finance', [FinanceController::class, 'page'])->middleware('admin.permission:finance.view')->name('finance');
        Route::get('catalog', [CatalogOperationsController::class, 'page'])->middleware('admin.permission:catalog.write')->name('catalog');
        Route::get('advanced', [AdvancedOperationsController::class, 'page'])->middleware('admin.permission:audit.view')->name('advanced');
        Route::get('users', ModuleWorkspaceController::class)->defaults('module', 'users')->middleware('admin.permission:users.view')->name('users');
        Route::get('finance-records', ModuleWorkspaceController::class)->defaults('module', 'finance-records')->middleware('admin.permission:finance.view')->name('finance-records');
        Route::get('records/{entity}/{record}', [CanonicalDetailController::class, 'show'])->name('record');
        Route::get('users/{user}', [UserOperationsController::class, 'show'])->middleware('admin.permission:users.view')->name('users.show');
        Route::get('reels-live', ModuleWorkspaceController::class)->defaults('module', 'reels-live')->middleware('admin.permission:moderation.act')->name('reels-live');
        Route::get('community', ModuleWorkspaceController::class)->defaults('module', 'community')->middleware('admin.permission:moderation.act')->name('community');
        Route::get('communications', ModuleWorkspaceController::class)->defaults('module', 'communications')->middleware('admin.permission:broadcast.send')->name('communications');
        Route::get('communications/compose', [CommunicationsWorkspaceController::class, 'index'])->middleware('admin.permission:broadcast.send')->name('communications.compose');
        Route::get('growth', ModuleWorkspaceController::class)->defaults('module', 'growth')->middleware('admin.permission:settings.write')->name('growth');
        Route::get('cms', ModuleWorkspaceController::class)->defaults('module', 'cms')->middleware('admin.permission:settings.write')->name('cms');
        Route::get('ai', ModuleWorkspaceController::class)->defaults('module', 'ai')->middleware('admin.permission:ai.manage')->name('ai');
        Route::get('support', ModuleWorkspaceController::class)->defaults('module', 'support')->middleware('admin.permission:users.view')->name('support');
        Route::get('support/tickets/{ticket}', [SupportWorkspaceController::class, 'show'])->middleware('admin.permission:users.view')->name('support.ticket');
        Route::get('analytics', ModuleWorkspaceController::class)->defaults('module', 'analytics')->middleware('admin.permission:audit.view')->name('analytics');
        Route::get('settings', ModuleWorkspaceController::class)->defaults('module', 'settings')->middleware('admin.permission:settings.write')->name('settings');
        Route::get('settings/configuration', [ConfigurationWorkspaceController::class, 'index'])->middleware('admin.permission:settings.write')->name('settings.configuration');
        Route::get('settings/integrations', [IntegrationSettingsController::class, 'page'])->middleware('admin.permission:settings.write')->name('settings.integrations');
        Route::get('audit', ModuleWorkspaceController::class)->defaults('module', 'audit')->middleware('admin.permission:audit.view')->name('audit');
        Route::get('profile', [AdminAccountController::class, 'show'])->name('profile');
        Route::patch('profile', [AdminAccountController::class, 'update']);
        Route::delete('sessions/{session}', [AdminAccountController::class, 'revokeSession'])->name('sessions.destroy');
        Route::post('logout', [AuthController::class, 'destroy'])->name('logout');
    });
});
