import { Head } from '@inertiajs/react';
import type React from 'react';

type Row={id?:string;state?:string;slug?:string;title?:string;subject?:string;priority?:string;type?:string;version?:number;cost_microusd?:number;total?:number;bytes?:number};
type Props={referrals:Row[];programs:Row[];cmsPages:Row[];aiJobs:Row[];aiUsage:{cost_microusd:number;jobs:number};prompts:Row[];tickets:Row[];feedback:Row[];broadcasts:Row[];deliveries:Row[];syncConflicts:Row[];backups:Row[];freshAt:string};

export default function Advanced(p:Props){
 const groups:[string,Row[]][]=[['Referral programs',p.programs],['Referral funnel',p.referrals],['CMS and merchandising',p.cmsPages],['AI jobs and safety',p.aiJobs],['Prompt rollouts',p.prompts],['Support inbox',p.tickets],['User feedback',p.feedback],['Notification broadcasts',p.broadcasts],['Delivery health',p.deliveries],['Sync conflicts',p.syncConflicts],['Encrypted backups',p.backups]];
 return <div className="min-h-screen bg-slate-950 text-slate-100"><Head title="Advanced operations"/><header className="border-b border-slate-800 px-6 py-5"><div className="mx-auto flex max-w-7xl items-end justify-between gap-4"><div><a href="/admin" className="text-xs font-bold tracking-[.2em] text-teal-300">PELEVO OPS</a><h1 className="mt-2 text-2xl font-semibold">Advanced platform operations</h1><p className="text-sm text-slate-400">Referrals, communications, CMS, AI, support, sync and privacy evidence.</p></div><div className="text-right text-xs text-slate-500"><b className="block text-teal-300">{p.aiUsage.jobs} AI jobs</b>{p.aiUsage.cost_microusd.toLocaleString()} µUSD<br/>{new Date(p.freshAt).toLocaleString()}</div></div></header><main className="mx-auto grid max-w-7xl gap-6 px-6 py-8 md:grid-cols-2 xl:grid-cols-3">{groups.map(([title,rows])=><Panel key={title} title={title} rows={rows}/>)}</main></div>;
}
function Panel({title,rows}:{title:string;rows:Row[]}){return <section className="rounded-xl border border-slate-800 bg-slate-900 p-4"><h2 className="flex justify-between font-semibold">{title}<span className="rounded-full bg-slate-800 px-2 py-1 text-xs">{rows.length}</span></h2><div className="mt-3 max-h-72 space-y-2 overflow-auto">{rows.length===0?<p className="rounded-lg border border-dashed border-slate-700 p-5 text-center text-sm text-slate-500">No records require attention.</p>:rows.map((r,i)=><article key={r.id??i} className="flex items-center justify-between gap-3 rounded-lg border border-slate-800 p-3"><div className="min-w-0"><b className="block truncate text-sm">{r.title??r.subject??r.slug??r.type??r.id??r.state}</b><small className="text-slate-500">{r.priority??(r.version?`Version ${r.version}`:'')}</small></div><Badge value={r.state??'recorded'}/></article>)}</div></section>}
function Badge({value}:{value:string}){return <span className="rounded-full bg-slate-800 px-2 py-1 text-[10px] uppercase text-teal-300">{value}</span>}
