import { Head, router } from '@inertiajs/react';
import { useState } from 'react';
import type React from 'react';
type Row={id:string;title:string;author?:string;status:string;feed_state?:string;last_success_at?:string;last_failure_at?:string;consecutive_failures?:number;last_error?:string};
type Page<T>={data:T[];current_page:number;last_page:number;total:number;prev_page_url?:string;next_page_url?:string};
type Item={id:number|string;name?:string;slug?:string;title?:string;term?:string;synonym?:string;active?:boolean;published?:boolean;position:number};
type HomeModule={id:string;key:string;title:string;subtitle?:string;kind:string;source:string;active:boolean;position:number;starts_at?:string;ends_at?:string};
type Props={shows:Page<Row>;feedHealth:{state:string;total:number}[];categories:Item[];playlists:Item[];homeModules:HomeModule[];searchSynonyms:Item[];zeroResults:{query:string;searches:number}[];filters:Record<string,string>;freshAt:string};
export default function Catalog(p:Props){
 const nav=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);router.get('/admin/catalog',Object.fromEntries(d.entries()) as Record<string,string>,{preserveState:true});};
 const refresh=async(id:string)=>{await mutate(`/api/admin/v1/catalog/shows/${id}/refresh`,'POST',{});router.reload();};
 return <div className="min-h-screen bg-slate-950 text-slate-100"><Head title="Catalog operations"/><header className="border-b border-slate-800 px-6 py-5"><div className="mx-auto max-w-7xl"><a href="/admin" className="text-xs font-bold tracking-[.2em] text-teal-300">PELEVO OPS</a><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold">Catalog and discovery</h1><p className="text-sm text-slate-400">RSS health, editorial programming, taxonomy and search relevance.</p></div><span className="text-xs text-slate-500">Updated {new Date(p.freshAt).toLocaleString()}</span></div></div></header><main className="mx-auto max-w-7xl space-y-8 px-6 py-8">
 <section className="grid gap-3 sm:grid-cols-4">{p.feedHealth.map(x=><div key={x.state} className="rounded-xl border border-slate-800 bg-slate-900 p-4"><b className="text-2xl">{x.total}</b><p className="text-xs uppercase text-slate-400">{x.state}</p></div>)}</section>
 <section><h2 className="mb-3 font-semibold">Show directory and RSS health</h2><form onSubmit={nav} className="mb-4 flex flex-wrap gap-2"><input aria-label="Search shows" name="q" defaultValue={p.filters.q} placeholder="Search title or publisher" className="rounded border border-slate-700 bg-slate-900 px-3 py-2"/><select aria-label="Feed state" name="feed_state" defaultValue={p.filters.feed_state??''} className="rounded border border-slate-700 bg-slate-900 px-3"><option value="">All feed states</option><option>healthy</option><option>failed</option><option>pending</option></select><select aria-label="Sort shows" name="sort" defaultValue={p.filters.sort??'updated_at'} className="rounded border border-slate-700 bg-slate-900 px-3"><option value="updated_at">Recently updated</option><option value="title">Title</option><option value="created_at">Created</option></select><button className="rounded bg-teal-500 px-4 py-2 font-semibold text-slate-950">Apply</button><a href="/admin/catalog" className="rounded border border-slate-700 px-4 py-2">Clear all</a></form><div className="overflow-x-auto rounded-xl border border-slate-800"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-slate-900 text-slate-400"><tr><th className="p-3">Show</th><th>Catalog</th><th>Feed</th><th>Last success</th><th>Action</th></tr></thead><tbody>{p.shows.data.map(x=><tr key={x.id} className="border-t border-slate-800"><td className="p-3"><a className="font-semibold text-teal-300 hover:underline" href={`/admin/records/shows/${x.id}`}>{x.title}</a><small className="block text-slate-500">{x.author||'Unknown publisher'}</small></td><td>{x.status}</td><td><span className="rounded-full bg-slate-800 px-2 py-1 text-xs">{x.feed_state||'unconfigured'}</span>{x.last_error&&<small className="block max-w-xs truncate text-red-300" title={x.last_error}>{x.last_error}</small>}</td><td>{x.last_success_at?new Date(x.last_success_at).toLocaleString():'Never'}</td><td><button onClick={()=>refresh(x.id)} className="rounded border border-teal-700 px-2 py-1 text-xs">Live refresh</button></td></tr>)}</tbody></table>{!p.shows.data.length&&<p className="p-8 text-center text-slate-500">No shows match these filters. Clear the filters to restore the directory.</p>}</div><div className="mt-3 flex justify-between text-sm"><span>{p.shows.total} shows</span><div className="space-x-2">{p.shows.prev_page_url&&<a href={p.shows.prev_page_url}>Previous</a>}{p.shows.next_page_url&&<a href={p.shows.next_page_url}>Next</a>}</div></div></section>
 <MergeDesk/><HomeMerchandising modules={p.homeModules}/><section className="grid gap-6 lg:grid-cols-3"><Panel title="Categories and tags">{p.categories.map(x=><Line key={x.id} a={x.name||''} b={x.active?'Active':'Hidden'}/>)}</Panel><Panel title="Editorial playlists">{p.playlists.map(x=><Line key={x.id} a={x.title||''} b={x.published?'Published':'Draft'}/>)}</Panel><Panel title="Search relevance"><h3 className="mb-2 text-xs uppercase text-slate-500">Synonyms</h3>{p.searchSynonyms.map(x=><Line key={x.id} a={x.term||''} b={x.synonym||''}/>)}<h3 className="mb-2 mt-4 text-xs uppercase text-slate-500">Zero-result searches</h3>{p.zeroResults.map(x=><Line key={x.query} a={x.query} b={String(x.searches)}/>)}</Panel></section>
 </main></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-xl border border-slate-800 bg-slate-900 p-4"><h2 className="mb-3 font-semibold">{title}</h2>{children||<p className="text-sm text-slate-500">No records before configuration.</p>}</section>}
function Line({a,b}:{a:string;b:string}){return <div className="flex justify-between border-t border-slate-800 py-2 text-sm"><span>{a}</span><span className="text-slate-400">{b}</span></div>}
async function mutate(url:string,method:string,body:object){const r=await fetch(url,{method,credentials:'same-origin',headers:{'Content-Type':'application/json',Accept:'application/json','X-CSRF-TOKEN':document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content??''},body:JSON.stringify(body)});if(!r.ok)throw new Error((await r.json()).error?.message??'Request failed');return r.json()}
function MergeDesk(){
 const [survivor,setSurvivor]=useState(''); const [duplicate,setDuplicate]=useState(''); const [preview,setPreview]=useState<Record<string,unknown>|null>(null);
 const inspect=async()=>{try{setPreview((await mutate('/api/admin/v1/catalog/merges/preview','POST',{survivor_show_id:survivor,duplicate_show_id:duplicate})).data)}catch(e){window.alert(String(e))}};
 const execute=async()=>{const reason=window.prompt('Reason for this governed merge');if(!reason||reason.length<10)return;try{const result=await mutate('/api/admin/v1/catalog/merges','POST',{survivor_show_id:survivor,duplicate_show_id:duplicate,confirmation:`MERGE ${duplicate}`,reason,idempotency_key:crypto.randomUUID()});window.alert(`Merge queued: ${result.data.merge_id}`)}catch(e){window.alert(String(e))}};
 return <Panel title="Duplicate merge preview and execution"><div className="grid gap-2 md:grid-cols-[1fr_1fr_auto_auto]"><input value={survivor} onChange={e=>setSurvivor(e.target.value)} placeholder="Survivor show ID" className="rounded border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/><input value={duplicate} onChange={e=>setDuplicate(e.target.value)} placeholder="Duplicate show ID" className="rounded border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/><button onClick={inspect} className="rounded border border-teal-700 px-3 text-sm">Preview</button><button disabled={!preview} onClick={execute} className="rounded bg-amber-500 px-3 text-sm font-semibold text-slate-950 disabled:opacity-40">Merge with MFA</button></div>{preview&&<pre className="mt-3 max-h-56 overflow-auto whitespace-pre-wrap rounded bg-slate-950 p-3 text-xs text-slate-400">{JSON.stringify(preview,null,2)}</pre>}</Panel>
}
function HomeMerchandising({modules}:{modules:HomeModule[]}){
 const [saving,setSaving]=useState<string|null>(null);
 const save=async(event:React.FormEvent<HTMLFormElement>,module:HomeModule)=>{event.preventDefault();setSaving(module.id);const data=Object.fromEntries(new FormData(event.currentTarget).entries());try{await mutate(`/api/admin/v1/catalog/home-modules/${module.id}`,'PUT',{title:data.title,subtitle:data.subtitle||null,position:Number(data.position),active:data.active==='on',starts_at:data.starts_at||null,ends_at:data.ends_at||null});router.reload()}catch(error){window.alert(String(error))}finally{setSaving(null)}};
 return <Panel title="Home merchandising"><p className="mb-4 text-sm text-slate-400">Order, schedule, title and publish system-owned Home rails. Source logic is immutable from this interface.</p><div className="space-y-3">{modules.map(module=><form key={module.id} onSubmit={event=>save(event,module)} className="grid gap-2 rounded-lg border border-slate-800 bg-slate-950/60 p-3 lg:grid-cols-[5rem_1fr_1fr_auto_auto]"><label className="grid gap-1 text-xs text-slate-400">Position<input name="position" type="number" min="0" max="1000" defaultValue={module.position} className="rounded border border-slate-700 bg-slate-900 px-2 py-2 text-slate-100"/></label><label className="grid gap-1 text-xs text-slate-400">Title<input name="title" required maxLength={150} defaultValue={module.title} className="rounded border border-slate-700 bg-slate-900 px-2 py-2 text-slate-100"/></label><label className="grid gap-1 text-xs text-slate-400">Subtitle<input name="subtitle" maxLength={250} defaultValue={module.subtitle} className="rounded border border-slate-700 bg-slate-900 px-2 py-2 text-slate-100"/></label><label className="flex items-center gap-2 self-end px-2 py-2 text-sm"><input name="active" type="checkbox" defaultChecked={module.active}/>Active</label><button disabled={saving!==null} className="self-end rounded bg-teal-500 px-3 py-2 text-sm font-semibold text-slate-950 disabled:opacity-40">{saving===module.id?'Saving…':'Save'}</button><label className="grid gap-1 text-xs text-slate-400 lg:col-start-2">Starts at<input name="starts_at" type="datetime-local" defaultValue={module.starts_at?.slice(0,16)} className="rounded border border-slate-700 bg-slate-900 px-2 py-2 text-slate-100"/></label><label className="grid gap-1 text-xs text-slate-400">Ends at<input name="ends_at" type="datetime-local" defaultValue={module.ends_at?.slice(0,16)} className="rounded border border-slate-700 bg-slate-900 px-2 py-2 text-slate-100"/></label><div className="text-xs text-slate-500 lg:col-span-5">{module.key} · {module.kind} · source: {module.source}</div></form>)}</div></Panel>
}
