import { Head, router } from '@inertiajs/react';
import { useState } from 'react';

type Claim = { id:string; show_title:string; claimant_name:string; method:string; state:string; destination_masked?:string; attempts:number; max_attempts:number; expires_at:string; live_evidence?:string|Record<string,unknown> };
type Detail = { claim:Claim; reviews:Array<Record<string,unknown>>; disputes:Array<Record<string,unknown>>; audits:Array<Record<string,unknown>> };

export default function Claims({ claims, freshAt }:{ claims:Claim[]; freshAt:string }) {
    const [selected, setSelected] = useState<Detail|null>(null);
    const [busy, setBusy] = useState(false);
    const headers = () => ({ Accept:'application/json', 'Content-Type':'application/json', 'X-CSRF-TOKEN':document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content ?? '' });
    const load = async (id:string) => { setBusy(true); const response=await fetch(`/api/admin/v1/claims/${id}`,{credentials:'same-origin',headers:headers()}); const body=await response.json(); setBusy(false); if(response.ok)setSelected(body.data); else window.alert(body.error?.message ?? 'Unable to load claim.'); };
    const live = async () => { if(!selected)return; setBusy(true); const response=await fetch(`/api/admin/v1/claims/${selected.claim.id}/live-rss`,{method:'POST',credentials:'same-origin',headers:headers()}); const body=await response.json(); setBusy(false); if(response.ok) await load(selected.claim.id); else window.alert(body.error?.message ?? 'Live fetch failed.'); };
    const reissue = async () => { if(!selected)return; const reason=window.prompt('Reason for requesting a new owner-email code'); if(!reason||reason.length<10)return; setBusy(true); const response=await fetch(`/api/admin/v1/claims/${selected.claim.id}/challenge`,{method:'POST',credentials:'same-origin',headers:headers(),body:JSON.stringify({reason})}); const body=await response.json(); setBusy(false); if(response.ok)await load(selected.claim.id); else window.alert(body.error?.message??'Code reissue failed.'); };
    const decide = async (decision:'approved'|'rejected'|'escalated') => { if(!selected)return; const reason=window.prompt(`Reason for ${decision}`); if(!reason||reason.length<10)return; setBusy(true); const response=await fetch(`/api/admin/v1/claims/${selected.claim.id}`,{method:'PUT',credentials:'same-origin',headers:headers(),body:JSON.stringify({decision,reason})}); const body=await response.json(); setBusy(false); if(response.ok){setSelected(null);router.reload();}else window.alert(body.error?.message ?? 'Decision failed.'); };
    const evidence = selected?.claim.live_evidence ? (typeof selected.claim.live_evidence === 'string' ? JSON.parse(selected.claim.live_evidence) : selected.claim.live_evidence) : null;
    return <div className="min-h-screen bg-slate-950 text-slate-100"><Head title="Creator claims" />
        <header className="border-b border-slate-800 px-6 py-5"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><a href="/admin" className="text-xs font-bold tracking-[.2em] text-teal-300">PELEVO OPS</a><h1 className="mt-2 text-2xl font-semibold">Creator claim review</h1></div><span className="text-xs text-slate-500">Updated {new Date(freshAt).toLocaleString()}</span></div></header>
        <main className="mx-auto grid max-w-7xl gap-6 px-6 py-8 lg:grid-cols-[minmax(0,1fr)_minmax(340px,.8fr)]">
            <section className="space-y-3"><h2 className="font-semibold">Open queue <span className="ml-2 rounded-full bg-slate-800 px-2 py-1 text-xs">{claims.length}</span></h2>{claims.map(claim=><button key={claim.id} onClick={()=>load(claim.id)} className="grid w-full grid-cols-[1fr_auto] gap-3 rounded-xl border border-slate-800 bg-slate-900 p-4 text-left hover:border-teal-500"><div><strong>{claim.show_title}</strong><p className="text-sm text-slate-300">Claimed by {claim.claimant_name}</p><p className="mt-1 text-xs text-slate-400">{claim.method} · {claim.destination_masked ?? 'description challenge'} · expires {new Date(claim.expires_at).toLocaleString()}</p></div><Badge value={claim.state}/></button>)}{!claims.length&&<p className="rounded-xl border border-dashed border-slate-700 p-8 text-center text-sm text-slate-500">No creator claims require review.</p>}</section>
            <section className="rounded-xl border border-slate-800 bg-slate-900 p-5">{busy&&!selected?<p>Loading…</p>:selected?<><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">{selected.claim.show_title}</h2><code className="text-xs text-slate-500">{selected.claim.id}</code></div><Badge value={selected.claim.state}/></div><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><dt className="text-slate-500">Method</dt><dd>{selected.claim.method}</dd><dt className="text-slate-500">Destination</dt><dd>{selected.claim.destination_masked ?? 'Not disclosed'}</dd><dt className="text-slate-500">Attempts</dt><dd>{selected.claim.attempts}/{selected.claim.max_attempts}</dd></dl><div className="mt-5 rounded-lg bg-slate-950 p-4"><h3 className="text-sm font-semibold">Live RSS evidence</h3>{evidence?<pre className="mt-2 whitespace-pre-wrap text-xs text-slate-400">{JSON.stringify(evidence,null,2)}</pre>:<p className="mt-2 text-xs text-slate-500">Not fetched yet.</p>}<button disabled={busy} onClick={live} className="mt-3 rounded-lg border border-teal-700 px-3 py-2 text-xs text-teal-300">Refresh from live RSS</button></div><div className="mt-5"><h3 className="text-sm font-semibold">Complete decision history</h3><pre className="mt-2 max-h-48 overflow-auto whitespace-pre-wrap rounded-lg bg-slate-950 p-3 text-xs text-slate-400">{JSON.stringify({reviews:selected.reviews,disputes:selected.disputes,audits:selected.audits},null,2)}</pre></div><div className="mt-5 flex flex-wrap gap-2"><Action onClick={()=>decide('approved')}>Approve</Action><Action onClick={()=>decide('rejected')}>Reject</Action><Action onClick={()=>decide('escalated')}>Open dispute</Action></div></>:<p className="text-sm text-slate-500">Select a claim to inspect its evidence and audit history.</p>}</section>
            {selected?.claim.method==='email'&&<button disabled={busy} onClick={reissue} className="rounded-lg border border-teal-700 px-3 py-2 text-xs text-teal-300 lg:col-start-2">Request new owner-email code</button>}
        </main></div>;
}
function Badge({value}:{value:string}){return <span className="h-fit rounded-full bg-slate-800 px-2 py-1 text-[11px] font-semibold uppercase tracking-wide text-teal-300">{value}</span>}
function Action({children,onClick}:{children:string;onClick:()=>void}){return <button onClick={onClick} className="rounded-lg border border-slate-700 px-3 py-2 text-xs font-semibold hover:border-teal-500 hover:text-teal-300">{children}</button>}
