import { Head, Link, router } from '@inertiajs/react';
import { useState, type FormEvent } from 'react';

type Template = { id: string; key: string; version: number; title: string; body: string };
type Broadcast = { id: string; state: string; scheduled_at: string; created_at: string };
export default function Communications({ templates, broadcasts, deliveryStates, freshAt, enabled }: { templates: Template[]; broadcasts: Broadcast[]; deliveryStates: { state: string; total: number }[]; freshAt: string; enabled: boolean }) {
  const [templateId, setTemplateId] = useState(templates[0]?.id ?? '');
  const [country, setCountry] = useState('');
  const [audience, setAudience] = useState<number | null>(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const [cancelId, setCancelId] = useState('');
  const template = templates.find(item => item.id === templateId);
  const headers = { Accept: 'application/json', 'Content-Type': 'application/json', 'X-CSRF-TOKEN': document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content ?? '' };
  const inspectAudience = async () => {
    setBusy(true); setMessage('');
    try { const response = await fetch(`/api/admin/v1/communications/audience?country=${encodeURIComponent(country)}`, { headers }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? 'Audience preview unavailable.'); setAudience(body.data.recipients); }
    catch (error) { setMessage(String(error)); } finally { setBusy(false); }
  };
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (audience === null) return; setBusy(true); setMessage('');
    const data = new FormData(event.currentTarget);
    try {
      const response = await fetch('/api/admin/v1/advanced/broadcasts', { method: 'POST', headers, body: JSON.stringify({ template_id: templateId, audience: country ? { country } : {}, scheduled_at: `${data.get('scheduled_at')}:00+00:00`, reason: data.get('reason') }) });
      const body = await response.json(); if (!response.ok) throw new Error(Object.values(body.error?.fields ?? {}).flat().join(' ') || body.error?.message || 'Unable to schedule the broadcast.');
      setMessage(`Broadcast ${body.data.broadcast.id} scheduled. Audit: ${body.data.audit_reference}`); setAudience(null); router.reload();
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Connection interrupted. Check scheduled broadcasts before retrying.'); } finally { setBusy(false); }
  };
  const cancel = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setBusy(true);
    try { const response = await fetch(`/api/admin/v1/communications/broadcasts/${cancelId}/cancel`, { method: 'POST', headers, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? 'Cancellation failed.'); setMessage(`Cancelled. Audit: ${body.data.audit_reference}`); setCancelId(''); router.reload(); } catch (error) { setMessage(String(error)); } finally { setBusy(false); }
  };
  const input = 'rounded-lg border border-slate-600 bg-slate-950 p-3 text-sm focus:border-teal-400 focus:outline-none';
  return <main className="mx-auto max-w-[1500px] p-5 sm:p-8"><Head title="Notification composer" /><Link href="/admin/communications" className="text-sm text-teal-300">Communications / Notifications</Link><header className="my-6 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-semibold">Notification studio</h1><p className="mt-2 text-sm text-slate-400">Preview the message and audience before scheduling delivery.</p></div><button onClick={() => router.reload()} className="rounded-lg border border-slate-700 px-4 py-2 text-sm">Refresh delivery status</button></header><p className="mb-5 text-xs text-slate-400">Updated {new Date(freshAt).toLocaleString()}</p>{!enabled && <p role="status" className="mb-5 rounded-xl border border-amber-800 p-4 text-amber-200">Notifications are disabled in this environment. Scheduling is unavailable.</p>}
    <section aria-label="Delivery summary" className="mb-6 grid gap-3 sm:grid-cols-4">{deliveryStates.map(item => <Link key={item.state} href={`/admin/communications?view=delivery-report&state=${item.state}`} className="rounded-xl border border-slate-800 bg-slate-900 p-4"><p className="text-xs uppercase text-slate-400">{item.state}</p><strong className="mt-2 block text-2xl">{item.total}</strong></Link>)}</section>
    <div className="grid gap-6 xl:grid-cols-[1fr_400px]"><form onSubmit={submit} className="grid gap-5 rounded-2xl border border-slate-800 p-6"><h2 className="font-semibold">Compose & schedule</h2><label className="grid gap-2 text-sm">Template version<select value={templateId} onChange={event => setTemplateId(event.target.value)} required className={input}><option value="">Select a template</option>{templates.map(item => <option key={item.id} value={item.id}>{item.key} · v{item.version}</option>)}</select></label>{!templates.length && <Link href="/admin/communications?view=templates" className="text-sm text-teal-300">Create a notification template first →</Link>}<label className="grid gap-2 text-sm">Recipient country (ISO code; blank for all active accounts)<input value={country} maxLength={2} pattern="[A-Z]{2}|" onChange={event => { setCountry(event.target.value.toUpperCase()); setAudience(null); }} className={input} placeholder="NG" /></label><button type="button" disabled={busy} onClick={() => void inspectAudience()} className="rounded-lg border border-teal-700 px-4 py-2 text-sm text-teal-300">Preview audience</button>{audience !== null && <p className="rounded-lg bg-teal-950 p-3 text-sm text-teal-200">{audience.toLocaleString()} active accounts currently match. Delivery evaluates the audience again at the scheduled time.</p>}<label className="grid gap-2 text-sm">Schedule (UTC)<input type="datetime-local" name="scheduled_at" required className={input} /></label><label className="grid gap-2 text-sm">Business reason<textarea name="reason" required minLength={10} maxLength={2000} className={input} /></label><label className="flex items-start gap-3 text-sm text-slate-300"><input type="checkbox" required className="mt-1 accent-teal-400" />I reviewed the audience and message preview and approve this broadcast.</label><button disabled={busy || audience === null || !template || !enabled} className="rounded-lg bg-teal-400 px-4 py-3 font-semibold text-slate-950 disabled:opacity-40">{busy ? 'Working…' : 'Schedule broadcast with MFA'}</button></form>
    <aside className="space-y-5"><section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6"><p className="text-xs font-semibold uppercase tracking-widest text-teal-300">Message preview</p><div className="mt-5 rounded-xl border border-slate-700 bg-slate-950 p-5"><p className="text-xs text-slate-400">PELEVO · In-app notification</p><h2 className="mt-3 font-semibold">{template?.title ?? 'Choose a template'}</h2><p className="mt-2 whitespace-pre-wrap text-sm text-slate-300">{template?.body}</p></div></section>{message && <p role="status" className="break-words rounded-xl border border-amber-800 p-4 text-sm text-amber-200">{message}</p>}{cancelId && <form onSubmit={cancel} className="grid gap-3 rounded-xl border border-amber-800 p-4"><h2 className="font-semibold">Cancel scheduled broadcast</h2><label className="grid gap-2 text-sm">Reason<textarea name="reason" required minLength={10} maxLength={2000} className={input} /></label><button disabled={busy} className="rounded-lg bg-amber-300 px-4 py-2 font-semibold text-slate-950">Confirm cancellation</button><button type="button" onClick={() => setCancelId('')} className="text-sm text-slate-400">Keep broadcast</button></form>}</aside></div>
    <section className="mt-6 rounded-2xl border border-slate-800 p-6"><h2 className="font-semibold">Recent broadcasts</h2>{broadcasts.length ? <ul className="mt-4 divide-y divide-slate-800">{broadcasts.map(item => <li key={item.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><Link href={`/admin/communications?view=scheduled&q=${item.id}`} className="font-mono text-xs text-teal-300">{item.id}</Link><p className="mt-2 text-xs text-slate-400">{new Date(item.scheduled_at).toLocaleString()} · {item.state}</p></div>{item.state === 'scheduled' && <button onClick={() => setCancelId(item.id)} className="rounded-lg border border-amber-800 px-3 py-2 text-sm text-amber-200">Cancel broadcast</button>}</li>)}</ul> : <p className="mt-4 text-sm text-slate-400">No broadcasts have been scheduled.</p>}</section>
  </main>;
}
