import { Head, Link, router } from '@inertiajs/react';
import { useState, type FormEvent } from 'react';

type Point = { date: string; value: number; previous_date: string; previous: number };
type Chart = { label: string; href: string; points: Point[] };
type Props = { metricGroups: Record<string, Record<string, number>>; incidents: { href: string; severity: string; label: string; count: number }[]; recentAudit: { id: string; action: string; reason?: string; created_at: string }[]; configVersion: number | null; freshAt: string; environment: string; charts: Chart[]; filters: { date_from: string; date_to: string } };
const sources: Record<string, string> = { audience: '/admin/users', listening: '/admin/users?view=listening', catalog: '/admin/catalog', creators: '/admin/creators', moderation: '/admin/reels-live', money: '/admin/finance-records', operations: '/admin/audit' };
const metricSources: Record<string, string> = { queued_jobs: '/admin/audit?view=queue', failed_jobs: '/admin/audit?view=failed-jobs', pending_uploads: '/admin/settings?view=media', earn_liability: '/admin/finance-records?view=accounts', open_claims: '/admin/claims', claim_disputes: '/admin/creators', open_reports: '/admin/community?view=reports&state=open', processing_reels: '/admin/reels-live?view=reels&state=processing', live_now: '/admin/reels-live?view=live&state=live', withdrawals_queued: '/admin/finance-records?view=withdrawals&state=queued', receipt_exceptions: '/admin/finance-records?view=receipts', reconciliation_drift: '/admin/finance-records?view=reconciliation&state=open', unhealthy_feeds: '/admin/catalog?feed_state=failed' };

export default function Dashboard({ metricGroups, incidents, recentAudit, configVersion, freshAt, environment, charts, filters }: Props) {
  const [busy, setBusy] = useState(false);
  const refresh = () => { setBusy(true); router.reload({ onFinish: () => setBusy(false) }); };
  const apply = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); router.get('/admin', Object.fromEntries(new FormData(event.currentTarget)) as Record<string, string>); };
  return <main className="mx-auto min-w-0 max-w-[1800px] p-5 sm:p-8"><Head title="Command Center" />
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold tracking-[.18em] text-teal-300">OPERATIONS / COMMAND CENTER</p><h1 className="mt-2 text-3xl font-semibold">Platform pulse</h1><p className="mt-2 text-sm text-slate-400">Updated {new Date(freshAt).toLocaleString()}</p></div><span className="rounded-full border border-amber-700/60 bg-amber-950/50 px-3 py-1 text-xs font-bold uppercase text-amber-300">{environment} · CONFIG v{configVersion ?? '—'}</span></header>
    <form onSubmit={apply} className="mt-6 flex flex-wrap items-end gap-3 rounded-xl border border-slate-800 bg-slate-900/40 p-4"><label className="grid gap-2 text-xs text-slate-400">Trend start<input aria-label="Trend start" type="date" name="date_from" defaultValue={filters.date_from} required className="rounded-lg border border-slate-600 bg-slate-950 px-3 py-2 text-sm text-slate-100" /></label><label className="grid gap-2 text-xs text-slate-400">Trend end<input aria-label="Trend end" type="date" name="date_to" defaultValue={filters.date_to} required className="rounded-lg border border-slate-600 bg-slate-950 px-3 py-2 text-sm text-slate-100" /></label><button className="rounded-lg bg-teal-400 px-4 py-2 text-sm font-semibold text-slate-950">Compare periods</button><button type="button" disabled={busy} onClick={refresh} className="rounded-lg border border-slate-600 px-4 py-2 text-sm disabled:opacity-50">{busy ? 'Refreshing…' : 'Refresh'}</button><span className="text-xs text-slate-400">Trends compare the previous period of equal length. Status cards show current platform totals.</span></form>
    {incidents.length > 0 && <section aria-label="Current incidents" className="mt-6 grid gap-3 md:grid-cols-2">{incidents.map(incident => <Link href={incident.href} key={incident.label} className="flex items-center justify-between rounded-xl border border-amber-900/70 bg-amber-950/20 p-4"><div><p className="text-xs uppercase text-amber-400">{incident.severity}</p><p className="font-medium">{incident.label}</p></div><strong className="text-2xl">{incident.count}</strong></Link>)}</section>}
    <section aria-label="Current status" className="mt-6 grid gap-5 md:grid-cols-2 2xl:grid-cols-3">{Object.entries(metricGroups).map(([group, metrics]) => <article key={group} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><h2 className="mb-4 text-sm font-bold uppercase tracking-[.14em] text-slate-400">{group}</h2><div className="grid grid-cols-2 gap-3">{Object.entries(metrics).map(([label, value]) => <Link key={label} href={metricSources[label] ?? sources[group]} className="rounded-xl border border-transparent bg-slate-950/70 p-4 transition hover:border-teal-800"><span className="text-xs text-slate-400">{label === 'hours_recorded' ? 'Stored playback positions (hours)' : label.replaceAll('_', ' ')}</span><strong className="mt-2 block text-2xl tabular-nums">{value.toLocaleString()}</strong><span className="mt-2 block text-[10px] text-teal-300">View source →</span></Link>)}</div></article>)}</section>
    <section aria-label="Period trends" className="mt-6 grid gap-5 xl:grid-cols-2">{charts.map(chart => <Trend key={chart.label} chart={chart} />)}</section>
    <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><h2 className="font-semibold">Recent governed activity</h2>{recentAudit.length === 0 ? <p className="mt-4 text-sm text-slate-400">No audit activity is available in your current access scope.</p> : <ol className="mt-4 divide-y divide-slate-800">{recentAudit.map(event => <li key={event.id} className="flex flex-wrap justify-between gap-3 py-3 text-sm"><div><Link href={`/admin/audit?q=${event.id}`} className="font-semibold text-teal-300">{event.action}</Link><p className="text-slate-400">{event.reason || 'No reason recorded'}</p></div><time className="text-xs text-slate-400">{new Date(event.created_at).toLocaleString()}</time></li>)}</ol>}</section>
  </main>;
}
function Trend({ chart }: { chart: Chart }) {
  const maximum = Math.max(1, ...chart.points.flatMap(point => [point.value, point.previous]));
  const polyline = (field: 'value' | 'previous') => chart.points.map((point, index) => `${10 + index * 580 / Math.max(1, chart.points.length - 1)},${170 - point[field] / maximum * 150}`).join(' ');
  const total = chart.points.reduce((sum, point) => sum + point.value, 0);
  const previous = chart.points.reduce((sum, point) => sum + point.previous, 0);
  return <article className="min-w-0 rounded-2xl border border-slate-800 bg-slate-900/40 p-5"><header className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{chart.label}</h2><p className="mt-2 text-2xl font-semibold tabular-nums">{total.toLocaleString()} <span className="text-xs font-normal text-slate-400">Previous: {previous.toLocaleString()}</span></p></div><Link href={chart.href} className="text-sm text-teal-300">Open matching records →</Link></header><svg viewBox="0 0 600 190" role="img" aria-label={`${chart.label}: current period total ${total}, previous period ${previous}. Exact daily values follow.`} className="mt-5 w-full"><path d="M10 20H590M10 95H590M10 170H590" stroke="#cbd5e1" strokeWidth="1" /><polyline points={polyline('previous')} fill="none" stroke="#94a3b8" strokeWidth="2" strokeDasharray="5 5" /><polyline points={polyline('value')} fill="none" stroke="#2dd4bf" strokeWidth="3" /></svg><p className="text-xs text-slate-400"><span className="text-teal-300">Solid: selected period</span> · Dashed: previous period</p><details className="mt-4"><summary className="cursor-pointer text-sm text-teal-300">Exact daily values</summary><div className="mt-3 max-h-64 overflow-auto"><table className="w-full text-left text-xs"><thead><tr><th className="py-2">Date</th><th>Value</th><th>Previous date</th><th>Previous value</th></tr></thead><tbody>{chart.points.map(point => <tr key={point.date} className="border-t border-slate-800"><td className="py-2">{point.date}</td><td>{point.value.toLocaleString()}</td><td>{point.previous_date}</td><td>{point.previous.toLocaleString()}</td></tr>)}</tbody></table></div></details></article>;
}
