import { Head, Link, router } from '@inertiajs/react';
import { useState, type FormEvent } from 'react';

import { useUnsavedChanges } from '../../components/admin/useUnsavedChanges';

type Props = { links: { id: string; label: string; href: string; target_id: string; reason: string }[]; linkTypes: { key: string; label: string }[]; ticket: { id: string; subject: string; message: string; state: string; priority: string; version: number; assigned_admin_id: string | null; sla_due_at: string | null; created_at: string }; requester: { id: string; name: string; handle: string; status: string }; attachments: { id: string; name: string; size: number; created_at: string }[]; notes: { id: string; public_reply: boolean; body: string; author: string; created_at: string }[]; audit: { id: string; action: string; reason: string; created_at: string }[]; assignees: { id: string; name: string }[]; freshAt: string };
export default function SupportTicket({ ticket, requester, notes, attachments, links, linkTypes, audit, assignees, freshAt }: Props) {
  const [busy, setBusy] = useState(false);
  const [dirty, setDirty] = useState(false);
  const [result, setResult] = useState('');
  const [conflict, setConflict] = useState(false);
  useUnsavedChanges(dirty);
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setBusy(true); setResult('');
    const form = event.currentTarget;
    try {
      const response = await fetch(`/api/admin/v1/support/tickets/${ticket.id}`, { method: 'PUT', headers: { Accept: 'application/json', 'Content-Type': 'application/json', 'X-CSRF-TOKEN': document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content ?? '' }, body: JSON.stringify({ ...Object.fromEntries(new FormData(form)), version: ticket.version }) });
      const body = await response.json();
      if (!response.ok) { setConflict(response.status === 409); throw new Error(Object.values(body.error?.fields ?? {}).flat().join(' ') || body.error?.message || 'Save failed. Retry when the connection is restored.'); }
      setResult(`Ticket updated. Audit reference: ${body.data.audit_reference}`); setDirty(false); setConflict(false); form.reset(); router.reload();
    } catch (error) { setResult(error instanceof Error ? error.message : 'Connection interrupted. Your changes remain in the form.'); }
    finally { setBusy(false); }
  };
  const attach = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = event.currentTarget; setBusy(true); setResult('');
    try {
      const response = await fetch(`/api/admin/v1/support/tickets/${ticket.id}/attachments`, { method: 'POST', headers: { Accept: 'application/json', 'X-CSRF-TOKEN': document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content ?? '' }, body: new FormData(form) });
      const body = await response.json();
      if (!response.ok) throw new Error(Object.values(body.error?.fields ?? {}).flat().join(' ') || body.error?.message || 'Attachment upload failed.');
      form.reset(); setResult('Private attachment added.'); router.reload();
    } catch (error) { setResult(error instanceof Error ? error.message : 'Upload interrupted. Please retry.'); }
    finally { setBusy(false); }
  };
  const linkRecord = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = event.currentTarget; setBusy(true); setResult('');
    try {
      const response = await fetch(`/api/admin/v1/support/tickets/${ticket.id}/links`, { method: 'POST', headers: { Accept: 'application/json', 'Content-Type': 'application/json', 'X-CSRF-TOKEN': document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content ?? '' }, body: JSON.stringify(Object.fromEntries(new FormData(form))) });
      const body = await response.json();
      if (!response.ok) throw new Error(body.error?.message || 'Record not found or unavailable to your role.');
      form.reset(); setResult('Related record linked and audited.'); router.reload();
    } catch (error) { setResult(error instanceof Error ? error.message : 'Link could not be saved.'); }
    finally { setBusy(false); }
  };
  const input = 'rounded-lg border border-slate-600 bg-slate-950 p-3 text-sm text-slate-100 focus:border-teal-400 focus:outline-none';
  return <main className="mx-auto max-w-[1500px] p-5 sm:p-8"><Head title={ticket.subject} /><nav className="text-sm text-teal-300"><Link href="/admin/support">Support inbox</Link><span className="px-2 text-slate-500">/</span>Ticket</nav><header className="my-6"><div className="flex flex-wrap items-center gap-3"><span className="rounded-full bg-teal-950 px-3 py-1 text-xs uppercase text-teal-300">{ticket.state}</span><span className="text-xs uppercase text-amber-300">{ticket.priority} priority</span></div><h1 className="mt-3 text-3xl font-semibold">{ticket.subject}</h1><p className="mt-2 font-mono text-xs text-slate-400">{ticket.id} · Version {ticket.version} · Updated {new Date(freshAt).toLocaleString()}</p></header>
    <div className="grid gap-6 xl:grid-cols-[1fr_360px]"><div className="min-w-0 space-y-6"><section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6"><h2 className="font-semibold">Conversation</h2><div className="mt-4 rounded-xl bg-slate-950 p-5"><p className="text-xs text-slate-400">{requester.name} · {new Date(ticket.created_at).toLocaleString()}</p><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-7">{ticket.message}</p></div>{notes.filter(note => note.public_reply).map(note => <article key={note.id} className="mt-4 rounded-xl border border-teal-900 p-4"><p className="text-xs text-teal-300">{note.author} · Sent to requester · {new Date(note.created_at).toLocaleString()}</p><p className="mt-3 whitespace-pre-wrap text-sm leading-7">{note.body}</p></article>)}</section>
    <section className="rounded-2xl border border-slate-800 p-6"><h2 className="font-semibold">Private attachments</h2><p className="mt-2 text-xs text-slate-400">Administrator evidence only. Downloads are audited. Files are not sent to the requester.</p>{attachments.map(file => <a key={file.id} href={`/api/admin/v1/support/tickets/${ticket.id}/attachments/${file.id}`} className="mt-3 block break-words text-sm text-teal-300">{file.name} · {Math.ceil(file.size / 1024)} KB · Download</a>)}<form onSubmit={attach} className="mt-4 grid gap-3"><label className="grid gap-2 text-sm">Evidence file<input type="file" name="file" accept=".jpg,.jpeg,.png,.pdf,.txt" required className="rounded border border-slate-700 p-3" /></label><p className="text-xs text-slate-400">JPG, PNG, PDF or text, up to 5 MB. Download only; no inline execution.</p><label className="grid gap-2 text-sm">Evidence reason<input name="reason" required minLength={10} maxLength={2000} className={input} /></label><button disabled={busy} className="justify-self-start rounded-lg border border-teal-700 px-4 py-2 text-sm text-teal-300 disabled:opacity-50">Add private attachment</button></form></section>
    <section className="rounded-2xl border border-slate-800 p-6"><h2 className="font-semibold">Internal notes</h2><p className="mt-1 text-xs text-slate-400">Visible to administrators. These notes are not sent to the requester.</p>{notes.filter(note => !note.public_reply).length ? notes.filter(note => !note.public_reply).map(note => <article key={note.id} className="mt-4 border-l-2 border-teal-800 pl-4"><p className="text-xs text-slate-400">{note.author} · {new Date(note.created_at).toLocaleString()}</p><p className="mt-2 whitespace-pre-wrap break-words text-sm">{note.body}</p></article>) : <p className="mt-4 text-sm text-slate-400">No internal notes yet.</p>}</section>
    <section className="rounded-2xl border border-slate-800 p-6"><h2 className="font-semibold">Linked records & incidents</h2><p className="mt-2 text-xs text-slate-400">Links do not change the source record. Only evidence permitted by your role is visible.</p>{links.map(link => <article key={link.id} className="mt-4 border-l-2 border-teal-800 pl-4"><Link href={link.href} className="break-all text-sm text-teal-300">{link.label} · {link.target_id}</Link><p className="mt-2 text-sm text-slate-400">{link.reason}</p></article>)}<form onSubmit={linkRecord} className="mt-4 grid gap-3"><label className="grid gap-2 text-sm">Record type<select name="kind" required className={input}>{linkTypes.map(type => <option value={type.key} key={type.key}>{type.label}</option>)}</select></label><label className="grid gap-2 text-sm">Related record ID<input name="target_id" required maxLength={191} className={input} /></label><label className="grid gap-2 text-sm">Link reason<input name="reason" required minLength={10} maxLength={2000} className={input} /></label><button disabled={busy} className="justify-self-start rounded-lg border border-teal-700 px-4 py-2 text-sm text-teal-300 disabled:opacity-50">Link existing record</button></form></section>
    <section className="rounded-2xl border border-slate-800 p-6"><h2 className="font-semibold">Audit history</h2>{audit.length ? <ol className="mt-4 divide-y divide-slate-800">{audit.map(item => <li key={item.id} className="py-3"><p className="text-sm font-semibold">{item.action}</p><p className="mt-1 text-sm text-slate-400">{item.reason}</p><p className="mt-1 font-mono text-xs text-slate-500">{item.id} · {new Date(item.created_at).toLocaleString()}</p></li>)}</ol> : <p className="mt-4 text-sm text-slate-400">No administrator changes recorded.</p>}</section></div>
    <aside className="space-y-6"><section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><h2 className="font-semibold">Requester context</h2><Link href={`/admin/users/${requester.id}`} className="mt-3 block text-teal-300">{requester.name} → User 360</Link><p className="mt-2 text-sm text-slate-400">@{requester.handle} · {requester.status}</p><p className="mt-4 text-sm">SLA due: {ticket.sla_due_at ? new Date(ticket.sla_due_at).toLocaleString() : 'Not assigned'}</p></section>
    <form onSubmit={submit} onChange={() => setDirty(true)} className="grid gap-4 rounded-2xl border border-slate-800 p-5"><h2 className="font-semibold">Assignment & resolution</h2><label className="grid gap-2 text-sm">State<select name="state" defaultValue={ticket.state} className={input}>{['open', 'pending', 'resolved', 'closed'].map(state => <option key={state}>{state}</option>)}</select></label><label className="grid gap-2 text-sm">Priority<select name="priority" defaultValue={ticket.priority} className={input}>{['normal', 'high', 'urgent'].map(priority => <option key={priority}>{priority}</option>)}</select></label><label className="grid gap-2 text-sm">Assignee<select name="assigned_admin_id" defaultValue={ticket.assigned_admin_id ?? ''} className={input}><option value="">Unassigned</option>{assignees.map(admin => <option key={admin.id} value={admin.id}>{admin.name}</option>)}</select></label><label className="grid gap-2 text-sm">Internal note<textarea name="note" rows={4} maxLength={10000} className={input} /></label><label className="grid gap-2 text-sm">Reply to requester<textarea name="reply" rows={4} maxLength={10000} className={input} /></label><label className="flex items-start gap-2 text-sm"><input type="checkbox" name="confirm_reply" className="mt-1" />Send this reply as an in-app notification. Internal notes remain private.</label><label className="grid gap-2 text-sm">Reason for change<textarea name="reason" required minLength={10} maxLength={2000} className={input} /></label>{result && <p role="status" className="break-words text-sm text-amber-200">{result}</p>}{conflict && <button type="button" onClick={() => router.reload()} className="text-left text-sm text-teal-300">Reload latest ticket; keep my note</button>}<button disabled={busy} className="rounded-lg bg-teal-400 px-4 py-3 font-semibold text-slate-950 disabled:opacity-50">{busy ? 'Saving…' : 'Save ticket update'}</button></form></aside></div>
  </main>;
}
